// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class Banks
    {
        public Banks()
        {
            Sanatorium = new HashSet<Sanatorium>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? CityId { get; set; }
        public string Rs { get; set; }
        public string Address { get; set; }
        public string Unp { get; set; }
        public string Okpo { get; set; }
        public string Bic { get; set; }
        public string UserModif { get; set; }
        public DateTime? DateModif { get; set; }
        public string Primech { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<Sanatorium> Sanatorium { get; set; }
    }
}