// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class City
    {
        public City()
        {
            Banks = new HashSet<Banks>();
            Sanatorium = new HashSet<Sanatorium>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? CountryId { get; set; }
        public string Priznak { get; set; }
        public string UserMod { get; set; }
        public DateTime? DateMod { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Banks> Banks { get; set; }
        public virtual ICollection<Sanatorium> Sanatorium { get; set; }
    }
}