// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class Dogovor
    {
        public Dogovor()
        {
            SummDogZay = new HashSet<SummDogZay>();
        }

        public int Id { get; set; }
        public string Number { get; set; }
        public DateTime? DateDog { get; set; }
        public DateTime? DateStart { get; set; }
        public DateTime? DateEnd { get; set; }
        public int? SanatoriumId { get; set; }
        public string UserModif { get; set; }
        public DateTime? DateModif { get; set; }
        public string Primech { get; set; }
        public string PriznakClose { get; set; }
        public int? FillialId { get; set; }
        public int? TypeDogId { get; set; }
        public decimal? SummaDog { get; set; }
        public int? PriznakKontrol { get; set; }

        public virtual Sanatorium Sanatorium { get; set; }
        public virtual TypeDog TypeDog { get; set; }
        public virtual ICollection<SummDogZay> SummDogZay { get; set; }
    }
}