// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Child = new HashSet<Child>();
            Komissiya = new HashSet<Komissiya>();
            User = new HashSet<User>();
            Zayavlenie = new HashSet<Zayavlenie>();
        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int? PositionId { get; set; }
        public int? DepartmentId { get; set; }
        public int? FilialId { get; set; }
        public string Address { get; set; }
        public string Pol { get; set; }
        public string UserMod { get; set; }
        public DateTime? DateMod { get; set; }
        public DateTime? DateBirth { get; set; }
        public string Fiorp { get; set; }
        public string Fiodp { get; set; }
        public string Fiovp { get; set; }
        public string Fiotp { get; set; }
        public string Fiopp { get; set; }

        public virtual Department Department { get; set; }
        public virtual Fillial Filial { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<Child> Child { get; set; }
        public virtual ICollection<Komissiya> Komissiya { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Zayavlenie> Zayavlenie { get; set; }
    }
}