// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class Koef
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? DateStart { get; set; }
        public decimal? Value { get; set; }
        public string UserModif { get; set; }
        public DateTime? DateModif { get; set; }
        public string Primech { get; set; }
        public decimal? Control { get; set; }
        public decimal? Preduptejdenie { get; set; }
    }
}