// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class Komissiya
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? StatusId { get; set; }
        public string Priznak { get; set; }
        public string UserModific { get; set; }
        public DateTime? DateModific { get; set; }
        public string FiodatPad { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Naznach Status { get; set; }
    }
}