// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class Sanatorium
    {
        public Sanatorium()
        {
            Dogovor = new HashSet<Dogovor>();
            ZayavlenieSanatorium = new HashSet<Zayavlenie>();
            ZayavlenieTurOpe = new HashSet<Zayavlenie>();
        }

        public int Id { get; set; }
        public int? CityId { get; set; }
        public string Name { get; set; }
        public string Priznak { get; set; }
        public string UserMod { get; set; }
        public DateTime? DateMod { get; set; }
        public string SanatInd { get; set; }
        public string Address { get; set; }
        public string PostAddress { get; set; }
        public string Unp { get; set; }
        public string Phone { get; set; }
        public int? BankId { get; set; }

        public virtual Banks Bank { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Dogovor> Dogovor { get; set; }
        public virtual ICollection<Zayavlenie> ZayavlenieSanatorium { get; set; }
        public virtual ICollection<Zayavlenie> ZayavlenieTurOpe { get; set; }
    }
}