// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class TableZay
    {
        public int Id { get; set; }
        public int? ZayId { get; set; }
        public int? ChildId { get; set; }
        public string Priznak { get; set; }
        public string UserMod { get; set; }
        public DateTime? DateMod { get; set; }

        public virtual Child Child { get; set; }
        public virtual Zayavlenie Zay { get; set; }
    }
}