// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class TypeDog
    {
        public TypeDog()
        {
            Dogovor = new HashSet<Dogovor>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Primech { get; set; }
        public string UserModif { get; set; }
        public DateTime? DateModif { get; set; }

        public virtual ICollection<Dogovor> Dogovor { get; set; }
    }
}