// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HealthCore.Models
{
    public partial class Zayavlenie
    {
        public Zayavlenie()
        {
            SummDogZay = new HashSet<SummDogZay>();
            TableZay = new HashSet<TableZay>();
        }

        public int Id { get; set; }
        public int? NumberZ { get; set; }
        public DateTime? DateZ { get; set; }
        public int? EmployeeId { get; set; }
        public DateTime? S { get; set; }
        public DateTime? Po { get; set; }
        public int? ProtocolId { get; set; }
        public string Who { get; set; }
        public int? SanatoriumId { get; set; }
        public string Priznak { get; set; }
        public string UserMod { get; set; }
        public DateTime? DateMod { get; set; }
        public decimal? Summa { get; set; }
        public decimal? SummaDop { get; set; }
        public int? DogovorId { get; set; }
        public string NumberDog { get; set; }
        public DateTime? DateDog { get; set; }
        public int? TurOpeId { get; set; }
        public int? PriznakOplata { get; set; }
        public int? Anulirovano { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Protocol Protocol { get; set; }
        public virtual Sanatorium Sanatorium { get; set; }
        public virtual Sanatorium TurOpe { get; set; }
        public virtual ICollection<SummDogZay> SummDogZay { get; set; }
        public virtual ICollection<TableZay> TableZay { get; set; }
    }
}